### ISSUE TITLE
using usb-stick and remote control parallel

### ISSUE THREAD

**Issue by str3000** [moTo31/schellenberg-mqtt#1]
Hello,
thanks for the fantastic task and description here. I have two rollodrive 65 premium and it works fine with this software.
I'm using ioBroker and integrate it in the visu.
I'm already have a SmartfriendsBox and will scrap it now :-)

But I have one problem,
I will use one rollodrive with my remote control. 
If I connect the USB-stick with the rollodrive, there will loose the connection to the remote control.
If I couple rollodrive with the usb-stick, the remote control will loose the connection.

Is there any possibility to use both parallel?

**Comment by str3000** [comment]
I found the solution in the [LoPablos] wiki
My failure was to couble the devices directly
A hint in the documentation were helpful

**Comment by moTo31** [comment]
Hey @str3000 , Im glad it works for you now. I don't have a remote, so I cannot reproduce the behaviour. Could you explain what I should update in the documentation?
